apiVersion: v1
appVersion: V1.0
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: wari
version: 0.1.0
home: wari.zaakonline.nl
icon: wari.zaakonline.nl