apiVersion: v1
appVersion: V1.0
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
name: wari
version: 0.1.0
home: wari.zaakonline.nl
icon: wari.zaakonline.nl