apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-24T19:15:12.3191244Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: c860b1af96831908a11d8bcdcf01479cd2061a4aecaf26b5f9e23aa90f8a42c6
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2020-11-24T19:15:12.3340828Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
  wari:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-24T19:15:12.324205Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 844f85bf1042b3ab4934a9df84c2959d92eaf98b970216685d3fce7003b7417b
    home: wari.zaakonline.nl
    icon: wari.zaakonline.nl
    name: wari
    urls:
    - wari-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-24T19:15:12.3134669Z"
